const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

const OTP_REQUEST = 'OTP_REQUEST';
const OTP_REQUEST_SUCCESS = 'OTP_REQUEST_SUCCESS';
const OTP_REQUEST_FAILURE = 'OTP_REQUEST_FAILURE';
const SEND_SUCCESS_STATUS_OFF = 'SEND_SUCCESS_STATUS_OFF';

export {
    REGISTER_REQUEST,
    REGISTER_SUCCESS,
    REGISTER_FAILURE,
    CLOSE_NOTIFICATION,
    OTP_REQUEST,
    OTP_REQUEST_SUCCESS,
    OTP_REQUEST_FAILURE,
    SEND_SUCCESS_STATUS_OFF
}